-- ============================================================
-- measure.coffee profiles — Phase 6: Support ticket automation
-- ============================================================

-- -----------------------------------------------------------
-- SUPPORT TICKETS
-- -----------------------------------------------------------
CREATE TABLE public.support_tickets (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number         bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id               uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source                text NOT NULL CHECK (source IN ('chat', 'in_app_form', 'sms', 'email', 'manual')),
  source_thread_id      uuid REFERENCES public.chat_threads(id) ON DELETE SET NULL,
  source_message_id     uuid REFERENCES public.chat_messages(id) ON DELETE SET NULL,
  title                 text NOT NULL CHECK (length(trim(title)) > 0),
  description           text NOT NULL CHECK (length(trim(description)) > 0),
  category              text NOT NULL CHECK (category IN ('bug', 'account', 'billing', 'feature_request', 'how_to', 'other')),
  severity              text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  triage_status         text NOT NULL DEFAULT 'pending' CHECK (triage_status IN ('pending', 'needs_info', 'actionable', 'non_actionable', 'completed')),
  ticket_status         text NOT NULL DEFAULT 'new' CHECK (ticket_status IN ('new', 'triage', 'queued_engineering', 'in_progress', 'in_review', 'resolved', 'closed')),
  reporter_timezone     text,
  reporter_contact      jsonb NOT NULL DEFAULT '{}'::jsonb,
  triage_notes          text,
  resolution_summary    text,
  latest_customer_status text,
  last_user_notified_at timestamptz,
  resolved_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_support_tickets_user_created
  ON public.support_tickets(user_id, created_at DESC);

CREATE INDEX idx_support_tickets_status_updated
  ON public.support_tickets(ticket_status, updated_at DESC);

CREATE INDEX idx_support_tickets_triage_status
  ON public.support_tickets(triage_status, updated_at DESC);

-- -----------------------------------------------------------
-- ENGINEERING WORK ITEMS LINKED TO SUPPORT TICKETS
-- -----------------------------------------------------------
CREATE TABLE public.support_engineering_tasks (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  support_ticket_id     uuid NOT NULL UNIQUE REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  workflow_status       text NOT NULL DEFAULT 'queued' CHECK (workflow_status IN ('queued', 'in_progress', 'in_review', 'merged', 'released', 'cancelled')),
  repo_owner            text,
  repo_name             text,
  branch_name           text,
  pull_request_number   integer,
  pull_request_url      text,
  linked_issue_identifier text,
  operator_notes        text,
  merged_at             timestamptz,
  released_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_support_engineering_status
  ON public.support_engineering_tasks(workflow_status, updated_at DESC);

CREATE INDEX idx_support_engineering_repo_pr
  ON public.support_engineering_tasks(repo_owner, repo_name, pull_request_number)
  WHERE pull_request_number IS NOT NULL;

-- -----------------------------------------------------------
-- SUPPORT EVENTS (AUDIT TRAIL)
-- -----------------------------------------------------------
CREATE TABLE public.support_ticket_events (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  support_ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  actor_type        text NOT NULL CHECK (actor_type IN ('system', 'support_agent', 'operator', 'user', 'github_webhook')),
  actor_id          text,
  event_type        text NOT NULL,
  event_payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_support_ticket_events_ticket_created
  ON public.support_ticket_events(support_ticket_id, created_at ASC);

-- -----------------------------------------------------------
-- SUPPORT NOTIFICATIONS
-- -----------------------------------------------------------
CREATE TABLE public.support_notifications (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  support_ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  user_id           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  channel           text NOT NULL CHECK (channel IN ('in_app_chat', 'in_app_feed', 'email', 'sms')),
  delivery_status   text NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending', 'sent', 'failed')),
  message           text NOT NULL CHECK (length(trim(message)) > 0),
  delivered_at      timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_support_notifications_user_created
  ON public.support_notifications(user_id, created_at DESC);

-- -----------------------------------------------------------
-- UPDATED-AT TRIGGERS
-- -----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.touch_support_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_touch_support_tickets_updated_at ON public.support_tickets;
CREATE TRIGGER trg_touch_support_tickets_updated_at
  BEFORE UPDATE ON public.support_tickets
  FOR EACH ROW EXECUTE FUNCTION public.touch_support_updated_at();

DROP TRIGGER IF EXISTS trg_touch_support_engineering_updated_at ON public.support_engineering_tasks;
CREATE TRIGGER trg_touch_support_engineering_updated_at
  BEFORE UPDATE ON public.support_engineering_tasks
  FOR EACH ROW EXECUTE FUNCTION public.touch_support_updated_at();

-- -----------------------------------------------------------
-- ROW LEVEL SECURITY
-- -----------------------------------------------------------
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_engineering_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_notifications ENABLE ROW LEVEL SECURITY;

-- Tickets: users can create and read only their own support reports.
CREATE POLICY "Users can view own support tickets"
  ON public.support_tickets FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own support tickets"
  ON public.support_tickets FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role can manage support tickets"
  ON public.support_tickets FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Engineering tasks: users can read tasks tied to their own tickets.
CREATE POLICY "Users can view own support engineering tasks"
  ON public.support_engineering_tasks FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.support_tickets t
      WHERE t.id = support_ticket_id
        AND t.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert support engineering tasks for own tickets"
  ON public.support_engineering_tasks FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.support_tickets t
      WHERE t.id = support_ticket_id
        AND t.user_id = auth.uid()
    )
  );

CREATE POLICY "Service role can manage support engineering tasks"
  ON public.support_engineering_tasks FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Events: users can read timeline events for their own tickets.
CREATE POLICY "Users can view own support ticket events"
  ON public.support_ticket_events FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.support_tickets t
      WHERE t.id = support_ticket_id
        AND t.user_id = auth.uid()
    )
  );

CREATE POLICY "Service role can manage support ticket events"
  ON public.support_ticket_events FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Notifications: users can read notifications addressed to them.
CREATE POLICY "Users can view own support notifications"
  ON public.support_notifications FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage support notifications"
  ON public.support_notifications FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
